replicaCount: 1

image:
  repository: reconquest/snake-runner
  pullPolicy: Always
  tag: "0.8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

snake:
  docker_mode: "host" # valid values: "host" "dind"

  master_address: 'https://bitbucket.local'
  registration_token: 'registration-token-from-the-bitbucket-admin-panel'
  log:
    debug: false
    trace: false
  docker_volumes: []
