apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-secrets
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  SNAKE_MASTER_ADDRESS: {{ .Values.snake.master_address | b64enc }}
  SNAKE_REGISTRATION_TOKEN: {{ .Values.snake.registration_token | b64enc }}
