name: Build & Push snake-runner chart
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/helm-push-action@v3
      env:
        SOURCE_DIR: '.'
        CHART_FOLDER: 'snake-runner'
        CHARTMUSEUM_URL: 'https://helm.reconquest.io'
        CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
        CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
